config/routes.rb
Rails.application.routes.draw do
  resources :books do
	  resources :copies
  end
  devise_for :admins
  devise_for :users
  resources :editorials
  resources :authors
  resources :admins
  resources :users do
    resources :loans
  end
  resources :themes
  root 'home#index'
  get 'about', to: 'home#about'
  post 'users/:user_id/loans/:id/return', to: 'loans#return_loan'
  post 'users/:user_id/loans/:id/cancel', to: 'loans#cancel_loan'
  post 'users/:user_id/loans/add_loan', to: 'loans#add_loan'
  #HYBRID
  get '/admin/checkuser', to: 'admins#check_user'
  get 'users/:user_id/user_loans', to: 'loans#user_loans'
  get 'books/:book_id/notlended', to: 'copies#notlended'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/copy.rb
class Copy < ApplicationRecord
  belongs_to :book
  has_many :loans
  has_many :users, through: :loans

  def loansActive?
  	if self.loans.where(active: [1, 0]).size>0
  		true
  	else
  		false
  	end
  end
end

app/controllers/copies_controller.rb
class CopiesController < ApplicationController
	before_action :set_copy, only: [:show, :update, :destroy]
  def index
    @book = Book.find params[:book_id]
    if params[:page].present?
      @copies = @book.copies.paginate(:page => params[:page], :per_page => 10)
    else
      @copies = @book.copies.paginate(:page => 1, :per_page => 10)
    end
  end

  def notlended
    book = Book.find(params[:book_id])
    @copies = book.copies.where(lended: false)
  end

  def show
  end

  def new
  	@book = Book.find(params[:book_id])
    @copy = @book.copies.build
  end

  def edit
  	@book = Book.find(params[:book_id])
    @copy = @book.copies.find(params[:id])
    
  end

  def create
    @book = Book.find(params[:book_id])
    @copy = @book.copies.build(copy_params)

    respond_to do |format|
      if @copy.save
        format.html { redirect_to book_copies_path @book, notice: 'Copy was successfully created.' }
        format.json { render :show, status: :created, location: @copy.book }
      else
        format.html { render :new }
        format.json { render json: @copy.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @book = Book.find(params[:book_id])
    respond_to do |format|
      if @copy.update(copy_params)
        format.html { redirect_to book_copies_path @book, notice: 'Copy was successfully updated.' }
        format.json { render :show, status: :ok, location: @copy }
      else
        format.html { render :edit }
        format.json { render json: @copy.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @copy.destroy
    respond_to do |format|
      format.html { redirect_to copies_url, notice: 'Copy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_copy
      @copy = Copy.find(params[:id])
    end

    def copy_params
      params.require(:copy).permit(:year, :location, :book_id)
    end
end

app/helpers/copies_helper.rb
module CopiesHelper
end

app/views/copies/_form.html.erb
<%= form_for([@book, @copy], html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @copy.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
      <h4><%= pluralize(@copy.errors.count, "error") %> prohibieron el ejemplar de ser guardado:</h4>

      <ul>
      <% @copy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-lg-15">
      <%= f.date_field :year, class: "form-control", autofocus: true, :placeholder => 'Año...' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-15">
      <%= f.text_field :location, class: "form-control", :placeholder => 'Ubicación...' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-15">
      <%= f.submit "Guardar Ejemplar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/copies/edit.html.erb
<div class="page-header">
  <%= link_to book_copies_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <%= link_to book_copy_path(@copy), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editar Ejemplar</h1>
</div>

<%= render 'form' %>

app/views/copies/index.html.erb
<div class="page-header">
  <% if admin_signed_in? %>
    <%= link_to new_book_copy_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      Añadir Ejemplar
    <% end %>
  <% end %>
  
  <h1>Ejemplares</h1>
</div>

<% if admin_signed_in? %>


  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
              <th>Año</th>
              <th>Ubicación</th>
              <th>Libro</th>
              <th>En Préstamo?</th>
              <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <%= content_tag_for(:tr, @copies) do |copy| %>
              <td><%= copy.year %></td>
              <td><%= copy.location %></td>
              <td><%= copy.book.title %></td>
              <td>
                <% if copy.loansActive?  %>
                    Sí
                <% else %>
                    No
                <% end %>
              </td>
              <td><%= link_to 'Mostrar', book_copy_path(@book, copy) %></td>
          <td><%= link_to 'Editar', edit_book_copy_path(@book, copy) %></td>
          <td><%= link_to 'Eliminar', book_copy_path(@book,copy), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tbody>
    </table>

    <%= will_paginate @copies %>

  </div>
<% end %>

app/views/copies/new.html.erb
<div class="page-header">
  <%= link_to book_copies_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <h1>Añadir Ejemplar</h1>
</div>

<%= render 'form' %>

app/views/copies/show.html.erb
<div class="page-header">

  <%= link_to book_copies_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <% if admin_signed_in? %>
    <%= link_to edit_book_copy_path(@copy), class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Editar
    <% end %>
  <% end %>


  <h1>Ejemplar</h1>
</div>

<p><b>Fecha: </b><%= @copy.year %></p>
<p><b>Ubicación: </b><%= @copy.location %></p>
<p><b>Libro: </b><%= @copy.book.title %></p>
<p><b>Prestado? </b> 
<% if @copy.loansActive?  %>
    Sí
<% else %>
    No
<% end %>
</p>