config/routes.rb
Rails.application.routes.draw do
  resources :books do
	  resources :copies
  end
  devise_for :admins
  devise_for :users
  resources :editorials
  resources :authors
  resources :admins
  resources :users do
    resources :loans
  end
  resources :themes
  root 'home#index'
  get 'about', to: 'home#about'
  post 'users/:user_id/loans/:id/return', to: 'loans#return_loan'
  post 'users/:user_id/loans/:id/cancel', to: 'loans#cancel_loan'
  post 'users/:user_id/loans/add_loan', to: 'loans#add_loan'
  #HYBRID
  get '/admin/checkuser', to: 'admins#check_user'
  get 'users/:user_id/user_loans', to: 'loans#user_loans'
  get 'books/:book_id/notlended', to: 'copies#notlended'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :loans
  has_many :copies, through: :loans
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	def self.search(search)
		if search
			t = self.arel_table
			s = "%#{search}%"
			self.where(t[:name].matches(s))
		else
			self.all
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@loans = current_user.loans.where(active: [1, 0])
		if params[:page].present?
			@hist = current_user.loans.where(active: 2).paginate(:page => params[:page], :per_page => 10).order(:delivery_date)
		else
			@hist = current_user.loans.where(active: 2).paginate(:page => 1, :per_page => 10).order(:delivery_date)
		end
	end

	def index
		if params[:search].present?
			@users = User.search(params[:search]).paginate(:page => params[:page], :per_page => 10).order(:name)
		else
			@users = User.search(params[:search]).paginate(:page => 1, :per_page => 10).order(:name)
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_links.html.erb
<div class="links">
	<%- if controller_name != 'sessions' %>
	  <%= link_to "Iniciar Sesión", new_session_path(resource_name) %><br />
	<% end -%>

	<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
	  <%= link_to "Registrarse", new_registration_path(resource_name) %><br />
	<% end -%>

	<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
	  <%= link_to "Olvidaste tu contraseña?", new_password_path(resource_name) %><br />
	<% end -%>

	<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
	  <%= link_to "No recibiste instrucciones de confirmación?", new_confirmation_path(resource_name) %><br />
	<% end -%>

	<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
	  <%= link_to "No recibiste instrucciones de desbloqueo?", new_unlock_path(resource_name) %><br />
	<% end -%>

	<%- if devise_mapping.omniauthable? %>
	  <%- resource_class.omniauth_providers.each do |provider| %>
	    <%= link_to "Iniciar Sesión con #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
	  <% end -%>
	<% end -%>

</div>