config/routes.rb
Rails.application.routes.draw do
  resources :books do
	  resources :copies
  end
  devise_for :admins
  devise_for :users
  resources :editorials
  resources :authors
  resources :admins
  resources :users do
    resources :loans
  end
  resources :themes
  root 'home#index'
  get 'about', to: 'home#about'
  post 'users/:user_id/loans/:id/return', to: 'loans#return_loan'
  post 'users/:user_id/loans/:id/cancel', to: 'loans#cancel_loan'
  post 'users/:user_id/loans/add_loan', to: 'loans#add_loan'
  #HYBRID
  get '/admin/checkuser', to: 'admins#check_user'
  get 'users/:user_id/user_loans', to: 'loans#user_loans'
  get 'books/:book_id/notlended', to: 'copies#notlended'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, :content_type => /\Aimage/
	validates_attachment_file_name :avatar, :matches => [/png\Z/, /jpe?g\Z/]

	def self.search(search)
		if search
			t = self.arel_table
			s = "%#{search}%"
			self.where(t[:name].matches(s))
		else
			self.all
		end
	end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, :except => [:show, :index]

  # GET /authors
  # GET /authors.json
  def index
    if params[:page].present?
      @authors = Author.search(params[:search]).paginate(:page => params[:page], :per_page => 10).order(:name)
    else
      @authors = Author.search(params[:search]).paginate(:page => 1, :per_page => 10).order(:name)
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :avatar, :desc)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @author.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h4>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-lg-15">
      <%= f.text_field :name, class: "form-control", :placeholder => 'Nombre...'%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-15">
      <%= f.text_area :desc, class: "form-control", :placeholder => 'Descripción...'%>
    </div>
  </div>
  <div class="field field_avatar">
      <%= f.label :avatar, "Foto: " %>
      <%= f.file_field :avatar, :class => "inputfile" %>
      <label for="author_avatar" class="upload">Seleccionar Archivo</label>
  </div>
  
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-15">
      <%= f.submit "Guardar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/authors/edit.html.erb
<div class="page-header">
  <%= link_to authors_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <%= link_to @author, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editar autor</h1>
</div>

<%= render 'form' %>

app/views/authors/index.html.erb
<div class="page-header">
  <% if admin_signed_in? %>
    <%= link_to new_author_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      Añadir Autor
    <% end %>
  <% end %>
  <h1>Autores</h1>
</div>

<form>
  <div class="search-bar">
    <input type="text" class="form-control" name="search" placeholder="Buscar...">
    <input type="submit" value="+">
    </div>
</form>

<div class="wrap-container">
  <% @authors.each do |author| %>
    
    <%= link_to author, :class=>'author', :style => "background-image: url('#{author.avatar.url(:medium)}')" do %>
      <div class="author-bio">
        <h4><%= author.name %></h4>
        <p><b>Cantidad de Libros: </b> <%= author.books.size %></p>
        <p><%= truncate(author.desc, :length => 100) %></p>
      </div>
    <% end %>
  <% end %>
</div>

<%= will_paginate @authors %>




<!-- PARTE ADMINISTRADOR -->
  <% if admin_signed_in? %>
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
                <th>Name</th>
                <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <%= content_tag_for(:tr, @authors) do |author| %>
                <td><%= author.name %></td>
                <td><%= link_to 'Show', author %></td>
            <td><%= link_to 'Edit', edit_author_path(author) %></td>
            <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>

app/views/authors/new.html.erb
<div class="page-header">
  <%= link_to authors_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <h1>Nuevo autor</h1>
</div>

<%= render 'form' %>

app/views/authors/show.html.erb
<div class="page-header">
  <%= link_to authors_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <% if admin_signed_in? %>
    <%= link_to edit_author_path(@author), class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Editar
    <% end %>
  <% end %>
  <h1><%= @author.name %></h1>
</div>

<div class="author-column">
  <div style="background-image: url('<%= @author.avatar.url %>')" class="author-picture">
  </div>
  <div class="author-desc">
    <p><%= @author.desc %></p>
  </div>
</div>
<% if @author.books.size>0 %>
  <h2>Libros</h2>  
<% end %>

<div class="wrap-container">
  <% @author.books.paginate(:page => params[:page], :per_page => 10).each do |book| %>
    
    <%= link_to book, :class=>'author', :style => "background-image: url('#{book.avatar.url(:medium)}')" do %>
      <div class="author-bio">
        <h4><%= book.title %></h4>
        <p><%= truncate(book.description, :length => 100) %></p>
      </div>
    <% end %>
  <% end %>
</div>

<%= will_paginate @author.books.paginate(:page => params[:page], :per_page => 10) %>