config/routes.rb
Rails.application.routes.draw do
  resources :books do
	  resources :copies
  end
  devise_for :admins
  devise_for :users
  resources :editorials
  resources :authors
  resources :admins
  resources :users do
    resources :loans
  end
  resources :themes
  root 'home#index'
  get 'about', to: 'home#about'
  post 'users/:user_id/loans/:id/return', to: 'loans#return_loan'
  post 'users/:user_id/loans/:id/cancel', to: 'loans#cancel_loan'
  post 'users/:user_id/loans/add_loan', to: 'loans#add_loan'
  #HYBRID
  get '/admin/checkuser', to: 'admins#check_user'
  get 'users/:user_id/user_loans', to: 'loans#user_loans'
  get 'books/:book_id/notlended', to: 'copies#notlended'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/editorial.rb
class Editorial < ApplicationRecord
	has_many :books
end

app/controllers/editorials_controller.rb
class EditorialsController < ApplicationController
  before_action :set_editorial, only: [:show, :edit, :update, :destroy]

  # GET /editorials
  # GET /editorials.json
  def index
    @editorials = Editorial.all
  end

  # GET /editorials/1
  # GET /editorials/1.json
  def show
  end

  # GET /editorials/new
  def new
    @editorial = Editorial.new
  end

  # GET /editorials/1/edit
  def edit
  end

  # POST /editorials
  # POST /editorials.json
  def create
    @editorial = Editorial.new(editorial_params)

    respond_to do |format|
      if @editorial.save
        format.html { redirect_to @editorial, notice: 'Editorial was successfully created.' }
        format.json { render :show, status: :created, location: @editorial }
      else
        format.html { render :new }
        format.json { render json: @editorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /editorials/1
  # PATCH/PUT /editorials/1.json
  def update
    respond_to do |format|
      if @editorial.update(editorial_params)
        format.html { redirect_to @editorial, notice: 'Editorial was successfully updated.' }
        format.json { render :show, status: :ok, location: @editorial }
      else
        format.html { render :edit }
        format.json { render json: @editorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /editorials/1
  # DELETE /editorials/1.json
  def destroy
    @editorial.destroy
    respond_to do |format|
      format.html { redirect_to editorials_url, notice: 'Editorial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_editorial
      @editorial = Editorial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def editorial_params
      params.require(:editorial).permit(:name)
    end
end

app/helpers/editorials_helper.rb
module EditorialsHelper
end

app/views/editorials/_form.html.erb
<%= form_for(@editorial, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @editorial.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@editorial.errors.count, "error") %> prohibió esta editorial de ser guardada:</h4>

      <ul>
      <% @editorial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-lg-15">
      <%= f.text_field :name, class: "form-control", :placeholder => "Nombre..." %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-15">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/editorials/edit.html.erb
<div class="page-header">
  <%= link_to editorials_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <%= link_to @editorial, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editar editorial</h1>
</div>

<%= render 'form' %>

app/views/editorials/index.html.erb
<div class="page-header">
  <%= link_to new_editorial_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Nueva Editorial
  <% end %>
  <h1>Editoriales</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Nombre</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @editorials) do |editorial| %>
            <td><%= editorial.name %></td>
        <td><%= link_to 'Editar', edit_editorial_path(editorial) %></td>
        <td><%= link_to 'Eliminar', editorial, method: :delete, data: { confirm: 'Estás Seguro?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/editorials/new.html.erb
<div class="page-header">
  <%= link_to editorials_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New editorial</h1>
</div>

<%= render 'form' %>

app/views/editorials/show.html.erb
<div class="page-header">
  <%= link_to editorials_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <%= link_to edit_editorial_path(@editorial), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Editorial</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nombre:</dt>
  <dd><%= @editorial.name %></dd>

</dl>